// src/main.ts
import { bootstrapApplication } from '@angular/platform-browser';
import { RouteReuseStrategy } from '@angular/router';
import { IonicRouteStrategy, provideIonicAngular } from '@ionic/angular/standalone';
import { provideRouter, withPreloading, PreloadAllModules } from '@angular/router';
import { importProvidersFrom } from '@angular/core';
import { HTTP_INTERCEPTORS, HttpClientModule, provideHttpClient, withInterceptorsFromDi } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations'; // ✅ Active les animations Angular

import { routes } from './app/app.routes';
import { AppComponent } from './app/app.component';
import { AuthInterceptor } from './app/interceptors/auth.interceptor';

import { addIcons } from 'ionicons';
import {
  cart,
  cartSharp,
  addCircleOutline,
  cashOutline,
  logOutOutline,
  personOutline,
  storefrontOutline,
  cubeOutline,
  heartOutline,
  receiptOutline,
  peopleOutline,
  hammerOutline,
  fileTrayStackedOutline,
  logInOutline,
  personAddOutline,
  cartOutline,
  arrowBack,
  imageOutline,
  pricetagOutline,
  documentTextOutline,
  locationOutline,
  gridOutline,
  cameraOutline,
  folderOpenOutline,
  checkmarkCircleOutline,
  closeCircleOutline,
  trashOutline,
  refreshOutline,
  shareSocial,
  bagCheckOutline,
  remove,
  add,
  downloadOutline,
  calendarOutline,
  walletOutline,
  cardOutline,
  eyeOutline,
  car,
  createOutline,
  camera,
  lockClosedOutline,
  heart,
  lockClosed,
  mailOutline,
  close,
  eyeOffOutline,
  cloudUploadOutline,
  addOutline,
  warningOutline,
  closeCircle,
  playOutline,
  checkmarkCircle,
  pauseOutline,
  callOutline,
  searchOutline,
  repeatOutline,
  timeOutline,
  checkmarkDoneOutline,
  checkmarkOutline,
  closeOutline,
  time,
  arrowBackOutline,
  arrowForwardOutline,
  arrowForward,
  pencilOutline,
  chevronDownCircleOutline,
  expandOutline,
  imagesOutline,
  chevronBack,
  chevronForward,
  star,
  checkmark,
  trendingUp,        // ✅ ajouté
  trendingDown       // ✅ ajouté
} from 'ionicons/icons';

// ✅ Enregistrement de toutes les icônes utilisées
addIcons({
  'cart': cart,
  'cart-sharp': cartSharp,
  'add-circle-outline': addCircleOutline,
  'cash-outline': cashOutline,
  'log-out-outline': logOutOutline,
  'person-outline': personOutline,
  'storefront-outline': storefrontOutline,
  'cube-outline': cubeOutline,
  'heart-outline': heartOutline,
  'receipt-outline': receiptOutline,
  'people-outline': peopleOutline,
  'hammer-outline': hammerOutline,
  'file-tray-stacked-outline': fileTrayStackedOutline,
  'log-in-outline': logInOutline,
  'person-add-outline': personAddOutline,
  'cart-outline': cartOutline,
  'arrow-back': arrowBack,
  'image-outline': imageOutline,
  'pricetag-outline': pricetagOutline,
  'document-text-outline': documentTextOutline,
  'location-outline': locationOutline,
  'grid-outline': gridOutline,
  'camera-outline': cameraOutline,
  'folder-open-outline': folderOpenOutline,
  'checkmark-circle-outline': checkmarkCircleOutline,
  'close-circle-outline': closeCircleOutline,
  'trash-outline': trashOutline,
  'refresh-outline': refreshOutline,
  'share-social': shareSocial,
  'bag-check-outline': bagCheckOutline,
  'remove': remove,
  'add': add,
  'download-outline': downloadOutline,
  'calendar-outline': calendarOutline,
  'wallet-outline': walletOutline,
  'card-outline': cardOutline,
  'eye-outline': eyeOutline,
  'car': car,
  'create-outline': createOutline,
  'camera': camera,
  'lock-closed-outline': lockClosedOutline,
  'heart': heart,
  'lock-closed': lockClosed,
  'mail-outline': mailOutline,
  'close': close,
  'eye-off-outline': eyeOffOutline,
  'cloud-upload-outline': cloudUploadOutline,
  'add-outline': addOutline,
  'warning-outline': warningOutline,
  'close-circle': closeCircle,
  'play-outline': playOutline,
  'checkmark-circle': checkmarkCircle,
  'pause-outline': pauseOutline,
  'call-outline': callOutline,
  'search-outline': searchOutline,
  'repeat-outline': repeatOutline,
  'time-outline': timeOutline,
  'checkmark-done-outline': checkmarkDoneOutline,
  'checkmark-outline': checkmarkOutline,
  'close-outline': closeOutline,
  'time': time,
  'arrow-back-outline': arrowBackOutline,
  'arrow-forward-outline': arrowForwardOutline,
  'arrow-forward': arrowForward,
  'pencil-outline': pencilOutline,
  'chevron-down-circle-outline': chevronDownCircleOutline,
  'expand-outline': expandOutline,
  'images-outline': imagesOutline,
  'chevron-back': chevronBack,
  'chevron-forward': chevronForward,
  'star': star,
  'checkmark': checkmark,
  'trending-up': trendingUp,       // ✅ ajouté
  'trending-down': trendingDown    // ✅ ajouté
});

bootstrapApplication(AppComponent, {
  providers: [
    { provide: RouteReuseStrategy, useClass: IonicRouteStrategy },
    provideIonicAngular(),
    provideRouter(routes, withPreloading(PreloadAllModules)),
    importProvidersFrom(HttpClientModule),
    provideHttpClient(withInterceptorsFromDi()),

    provideAnimations(), // ✅ active les animations Angular

    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthInterceptor,
      multi: true,
    },
  ],
});
